import spark.ModelAndView;
import spark.template.velocity.VelocityTemplateEngine;

import java.util.HashMap;
import java.util.Map;

import static spark.Spark.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        staticFileLocation("/public");
        String layout = "templates/layout.vtl";

        ProcessBuilder process = new ProcessBuilder();
        Integer port;
        if (process.environment().get("PORT") != null) {
            port = Integer.parseInt(process.environment().get("PORT"));
        } else {
            port = 4567;
        }

        port(port);

        //get main page
        get("/", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("template", "templates/index.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //add animal form
        get("/addAnimal", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("template", "templates/addAnimal.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //get all animals
        get("/allAnimals", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("animals", Aminals.all());
            model.put("template", "templates/allAnimals.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //add animal
        //post: process new client form
        post("/addAnimal", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();

            Integer i = Integer.parseInt(request.queryParams("sightingid"));
            Sightings sightings = Sightings.find(i);
            String name = request.queryParams("name");
            Aminals newAnimal = new Aminals(name, sightings.getId());
            String url = String.format("/allAnimals", newAnimal.getId());
            response.redirect(url);
            model.put("template", "templates/success.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());


    }
}
